#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# # collecstatic on any start is fine for local setups
# python manage.py collectstatic --noinput > /dev/null

python manage.py migrate
while :
do
    python manage.py runserver_plus 0.0.0.0:8050
    sleep 1
done

