#!/bin/sh
set -o errexit

git submodule update --init --recursive

PWD="$(pwd)"
HA_IGL_P2_ROOT_DIR=${HA_IGL_P2_ROOT_DIR:-$PWD}

echo "HA_IGL_P2_ROOT_DIR=${HA_IGL_P2_ROOT_DIR}"

docker build .github-actions/bandit -t github-actions/bandit

docker run -it --rm -w "/ha-igl-p2" -v "$(pwd):/ha-igl-p2" github-actions/bandit "$@"
