services:
  localstack:
    <<: *localstack

  ganache-cli:
    <<: *ganache-cli

  document-store-contract:
    <<: *document-store-contract

  document-store-worker:
    <<: *document-store-service-environment
    container_name: tradetrust-document-store-worker
    ports:
      - '8080:8080'
    environment:
      CONTAINER_MODE: container

      UNPROCESSED_QUEUE_URL: http://tradetrust-localstack:10001/queue/unprocessed
      INVALID_BUCKET_NAME: invalid
      UNPROCESSED_BUCKET_NAME: unprocessed
      BATCH_BUCKET_NAME: batch

      HOST: 0.0.0.0
      PORT: 8080

      ISSUE_UNPROCESSED_BUCKET_NAME: issue-unprocessed
      ISSUE_BATCH_BUCKET_NAME: issue-batch
      ISSUE_INVALID_BUCKET_NAME: issue-invalid
      ISSUED_BUCKET_NAME: issued

      REVOKE_UNPROCESSED_BUCKET_NAME: revoke-unprocessed
      REVOKE_BATCH_BUCKET_NAME: revoke-batch
      REVOKE_INVALID_BUCKET_NAME: revoke-invalid
      REVOKED_BUCKET_NAME: revoked

      # integer value >= 1 and <= 20
      # 20 is an upper limit that aws sdk has
      MESSAGE_WAIT_TIME: 10
      MESSAGE_VISIBILITY_TIMEOUT: 60
      TRANSACTION_TIMEOUT_SECONDS: 600
      TRANSACTION_CONFIRMATION_THRESHOLD: 1

      # integer only value
      GAS_PRICE_LIMIT_GWEI: 200
      # positive float value >= 1.1
      GAS_PRICE_MULTIPLIER: 1.2
      # 100 MB
      BATCH_SIZE_BYTES: 104857600
      # 10 minutes
      BATCH_TIME_SECONDS: 600
      # number of attempts and interval between them in case of an unexpected error in RestoreBatch task
      RESTORE_ATTEMPTS: 10
      RESTORE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in ComposeBatch task
      COMPOSE_ATTEMPTS: 10
      COMPOSE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in SaveIssuedBatch task
      SAVE_ATTEMPTS: 10
      SAVE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in IssueBatch task
      ISSUE_ATTEMPTS: 10
      ISSUE_ATTEMPTS_INTERVAL_SECONDS: 60
      REVOKE_ATTEMPTS: 10
      REVOKE_ATTEMPTS_INTERVAL_SECONDS: 60
