#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"

if [ -n "${DATABASE_PASSWORD_PASSWORD_ENCRYPTED+x}" ]; then
  >&2 echo "DATABASE_PASSWORD_PASSWORD_ENCRYPTED is defined, decrypt DATABASE_PASSWORD"
        echo ${DATABASE_PASSWORD#"base64:"}| base64 -d > "/tmp/cipher.blob"
        DATABASE_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d || exit $?)"
    export POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
    export POSTGRES_USER="${DATABASE_USERNAME}"
    export POSTGRES_DB="${DATABASE_NAME}"
    export POSTGRES_HOST="${DATABASE_FQDN}"
    export POSTGRES_PORT="${DATABASE_PORT}"
fi

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
