#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app \
    --timeout=630 --graceful-timeout=600 \
    --workers=${APP_WORKER_COUNT:-2} --threads=10 \
    --max-requests=300 --max-requests-jitter=100
