#!/bin/sh

set -o errexit
set -o nounset

CELERY_FLOWER_USER="${CELERY_FLOWER_USER:-""}"
CELERY_FLOWER_PASSWORD="${CELERY_FLOWER_PASSWORD:-""}"
CELERY_FLOWER_PASSWORD_ENCRYPTED="${CELERY_FLOWER_PASSWORD_ENCRYPTED:-"false"}"

KMS_PREFIX="${KMS_PREFIX:-"kms+base64:"}"

if [[ -n "${CELERY_FLOWER_USER}" && -n "${CELERY_FLOWER_PASSWORD}" ]]; then
    if [[ "${CELERY_FLOWER_PASSWORD_ENCRYPTED}" == "true" ]]; then
        echo "${CELERY_FLOWER_PASSWORD#${KMS_PREFIX}}" | base64 -d > "/tmp/cipher.blob"
        CELERY_FLOWER_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d )"

        if [[ -z "${CELERY_FLOWER_PASSWORD}" ]]; then
            echo "Celery Password was supposed to be encrypted but we couldn't decrypt it"
            exit 255
        fi
    fi

    export FLOWER_BASIC_AUTH="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
fi

celery flower \
    --app=chambers_app.taskapp \
    --broker="${CELERY_BROKER_URL}"
