# Generated by Django 2.2.10 on 2020-11-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Please enter your email address here if you wish to be contacted  about your query or feedback. Do not enter your email address if you wish to remain anonymous.', max_length=200)),
                ('contact', models.TextField(blank=True, help_text='Please enter a phone number or other additional contact information to help us contact you about your query or feedback. Do not provide contact details if you wish to remain anonymous.', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Please enter your query or feedback here.', max_length=10000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
