export const REVOKE_UNPROCESSED_QUEUE_V2 = 'revoke-unprocessed-2.0';
export const REVOKE_UNPROCESSED_BUCKET_V2 = 'revoke-unprocessed-2.0';
export const REVOKE_BATCH_BUCKET_V2 = 'revoke-batch-2.0';
export const REVOKE_INVALID_BUCKET_V2 = 'revoke-invalid-2.0';
export const REVOKED_BUCKET_V2 = 'revoked-2.0';


export const ISSUE_UNPROCESSED_QUEUE_V2 = 'issue-unprocessed-2.0';
export const ISSUE_UNPROCESSED_BUCKET_V2 = 'issue-unprocessed-2.0';
export const ISSUE_BATCH_BUCKET_V2 = 'issue-batch-2.0';
export const ISSUE_INVALID_BUCKET_V2 = 'issue-invalid-2.0';
export const ISSUED_BUCKET_V2 = 'issued-2.0';


export const REVOKE_UNPROCESSED_QUEUE_V3 = 'revoke-unprocessed-3.0';
export const REVOKE_UNPROCESSED_BUCKET_V3 = 'revoke-unprocessed-3.0';
export const REVOKE_BATCH_BUCKET_V3 = 'revoke-batch-3.0';
export const REVOKE_INVALID_BUCKET_V3 = 'revoke-invalid-3.0';
export const REVOKED_BUCKET_V3 = 'revoked-3.0';


export const ISSUE_UNPROCESSED_QUEUE_V3 = 'issue-unprocessed-3.0';
export const ISSUE_UNPROCESSED_BUCKET_V3 = 'issue-unprocessed-3.0';
export const ISSUE_BATCH_BUCKET_V3 = 'issue-batch-3.0';
export const ISSUE_INVALID_BUCKET_V3 = 'issue-invalid-3.0';
export const ISSUED_BUCKET_V3 = 'issued-3.0';

const V2_CONFIG = {
  REVOKE_UNPROCESSED_QUEUE: REVOKE_UNPROCESSED_QUEUE_V2,
  REVOKE_UNPROCESSED_BUCKET: REVOKE_UNPROCESSED_BUCKET_V2,
  REVOKE_BATCH_BUCKET: REVOKE_BATCH_BUCKET_V2,
  REVOKE_INVALID_BUCKET: REVOKE_INVALID_BUCKET_V2,
  REVOKED_BUCKET: REVOKED_BUCKET_V2,

  ISSUE_UNPROCESSED_QUEUE: ISSUE_UNPROCESSED_QUEUE_V2,
  ISSUE_UNPROCESSED_BUCKET: ISSUE_UNPROCESSED_BUCKET_V2,
  ISSUE_BATCH_BUCKET: ISSUE_BATCH_BUCKET_V2,
  ISSUE_INVALID_BUCKET: ISSUE_INVALID_BUCKET_V2,
  ISSUED_BUCKET: ISSUED_BUCKET_V2
}

const V3_CONFIG = {
  REVOKE_UNPROCESSED_QUEUE: REVOKE_UNPROCESSED_QUEUE_V3,
  REVOKE_UNPROCESSED_BUCKET: REVOKE_UNPROCESSED_BUCKET_V3,
  REVOKE_BATCH_BUCKET: REVOKE_BATCH_BUCKET_V3,
  REVOKE_INVALID_BUCKET: REVOKE_INVALID_BUCKET_V3,
  REVOKED_BUCKET: REVOKED_BUCKET_V3,

  ISSUE_UNPROCESSED_QUEUE: ISSUE_UNPROCESSED_QUEUE_V3,
  ISSUE_UNPROCESSED_BUCKET: ISSUE_UNPROCESSED_BUCKET_V3,
  ISSUE_BATCH_BUCKET: ISSUE_BATCH_BUCKET_V3,
  ISSUE_INVALID_BUCKET: ISSUE_INVALID_BUCKET_V3,
  ISSUED_BUCKET: ISSUED_BUCKET_V3
}
export {
  V3_CONFIG,
  V2_CONFIG
}
