const REVOKE_UNPROCESSED_QUEUE = 'revoke-unprocessed';
const REVOKE_UNPROCESSED_BUCKET = 'revoke-unprocessed';
const REVOKE_BATCH_BUCKET = 'revoke-batch';
const REVOKE_INVALID_BUCKET = 'revoke-invalid';
const REVOKED_BUCKET = 'revoked';


const ISSUE_UNPROCESSED_QUEUE = 'issue-unprocessed';
const ISSUE_UNPROCESSED_BUCKET = 'issue-unprocessed';
const ISSUE_BATCH_BUCKET = 'issue-batch';
const ISSUE_INVALID_BUCKET = 'issue-invalid';
const ISSUED_BUCKET = 'issued';


export {
  REVOKE_UNPROCESSED_QUEUE,
  REVOKE_UNPROCESSED_BUCKET,
  REVOKE_BATCH_BUCKET,
  REVOKE_INVALID_BUCKET,
  REVOKED_BUCKET,

  ISSUE_UNPROCESSED_QUEUE,
  ISSUE_UNPROCESSED_BUCKET,
  ISSUE_BATCH_BUCKET,
  ISSUE_INVALID_BUCKET,
  ISSUED_BUCKET
}
