# Generated by Django 2.2.10 on 2020-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_auto_20200526_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodemessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="sent",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("accepted", "Accepted"),
                    ("disputed", "Disputed"),
                    ("rejected", "Rejected"),
                    ("acquitted", "Acquitted"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e", "Exporter"),
                    ("i", "Importer"),
                    ("c", "Chambers"),
                    ("o", "Other"),
                ],
                default="o",
                max_length=1,
            ),
        ),
    ]
