# Generated by Django 2.2.10 on 2020-06-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200605_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='document',
            name='origin_criteria',
            field=models.CharField(blank=True, choices=[('WO', 'WO'), ('WP', 'WP'), ('PSR', 'PSR'), ('other', 'Other')], default='', max_length=32, verbose_name='Origin Criteria'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.FTA', verbose_name='FTA'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('issued', 'Issued'), ('not-issued', 'Not issued'), ('accepted', 'Accepted'), ('disputed', 'Disputed'), ('rejected', 'Rejected'), ('acquitted', 'Acquitted'), ('expired', 'Expired'), ('error', 'Error')], default='draft', max_length=12),
        ),
    ]
