# Generated by Django 2.2.10 on 2020-07-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_oaurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="oa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.OaUrl",
            ),
        ),
    ]
