# Generated by Django 2.2.10 on 2020-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_oa'),
    ]

    operations = [
        migrations.AddField(
            model_name='oaurl',
            name='ciphertext',
            field=models.TextField(blank=True),
        ),
    ]
