# Generated by Django 2.2.10 on 2020-07-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20200706_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.FTA', verbose_name='FTA'),
        ),
    ]
