# Generated by Django 2.2.10 on 2020-07-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20200714_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oadetails',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisation'),
        ),
    ]
