# Generated by Django 2.2.10 on 2020-08-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_documentfile_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.FTA', verbose_name='FTA'),
        ),
    ]
