# Generated by Django 2.2.10 on 2020-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_auto_20200916_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('not-issued', 'Not issued'), ('incoming', 'Incoming')], default='draft', max_length=32, verbose_name='Workflow status'),
        ),
        migrations.AlterField(
            model_name='oadetails',
            name='key',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='oadetails',
            name='uri',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
