# Generated by Django 2.2.10 on 2020-12-08 15:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0037_documenthistoryitem_is_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geo_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
