# Generated by Django 2.2.10 on 2020-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='type',
            field=models.CharField(default='file', max_length=10),
            preserve_default=False,
        ),
    ]
