# Generated by Django 2.2.10 on 2020-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_verificationattempt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('QR', 'QR'), ('link', 'Direct link')], max_length=10),
        ),
    ]
