const OPEN_ATTESTATION_VERSION_ID_V2_SHORT: string = 'open-attestation/2.0';
const OPEN_ATTESTATION_VERSION_ID_V3_SHORT: string = 'open-attestation/3.0';
const DOCUMENT_STORE_PROOF_TYPE: string = 'DOCUMENT_STORE';

export {
  OPEN_ATTESTATION_VERSION_ID_V2_SHORT,
  OPEN_ATTESTATION_VERSION_ID_V3_SHORT,
  DOCUMENT_STORE_PROOF_TYPE
}

export default {
  DOCUMENT_STORE_PROOF_TYPE,
  OPEN_ATTESTATION_VERSION_ID_V2_SHORT,
  OPEN_ATTESTATION_VERSION_ID_V3_SHORT
}
